### ISSUE TITLE
Deploy with bonfire once instead of multiple times for each Konflux component

### ISSUE THREAD

**Issue by gwenneg** [gbenhaim/tekton-insights#23]
Hi!

My team has one app with 13 components in Konflux.

With [our current Konflux integration tests configuration](https://github.com/redhat-appstudio/tenants-config/blob/main/cluster/stone-prd-rh01/tenants/hcc-notifications-tenant/notifications-tekton-insights_integration_test.yaml), which relies on this repository, Konflux will try to reserve 13 ephemeral namespaces (one for each component) while we only need all these components to be deployed all at once in the same namespace.

Is there a way to replace the 13 deployments with a single one?

**Comment by ernesgonzalez33** [comment]
@gwenneg I will close this issue since this is related to a Konflux behaviour and not to this repo and you already created a Feature request there. Thank you very much for pointing this out
